ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ARTICLE_CREATED';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ARTICLE_UPDATED';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ARTICLE_STATUS_CHANGED';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ARTICLE_DELETED';
